import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import { Navbar } from '@/components/nav/Navbar';
import { AnnouncementBar } from '@/components/nav/AnnouncementBar';
import { Footer } from '@/components/footer/Footer';
import { ThemeProvider } from '@/components/theme/ThemeProvider';
import './globals.css';

/**
 * Flash-of-wrong-theme guard. next-themes only resolves the active
 * theme after hydration, so the first frame would render in the
 * default (light). Users who picked dark previously would see a single-
 * frame flash before the class applies. This inline script runs at
 * parse time, reads the stored preference, and adds the `dark` class
 * to <html> before React mounts. Match the storage key next-themes
 * uses internally (`theme`).
 */
const noFlashScript = `(function(){try{var t=localStorage.getItem('theme');var d=window.matchMedia('(prefers-color-scheme: dark)').matches;var r=(t==='system'||!t)?(d?'dark':'light'):t;if(r==='dark'){document.documentElement.classList.add('dark');document.documentElement.style.colorScheme='dark';}}catch(e){}})();`;

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  metadataBase: new URL('https://reshelvs.com'),
  title: {
    default: 'Reshelvs — the operating system for FMCG field teams',
    template: '%s · Reshelvs',
  },
  description:
    'Reshelvs is the modern platform for FMCG field merchandising — routes, store visits, on-shelf availability, and field reports in one place. Built for reps, supervisors, and brand owners.',
  // Canonical for the home page. Child routes set their own via
  // pageMetadata(title, description, path) and override this.
  alternates: { canonical: '/' },
  keywords: [
    'FMCG',
    'field merchandising',
    'route planning',
    'store visits',
    'on-shelf availability',
    'OSA',
    'sales force automation',
    'SFA',
    'field execution',
    'merchandiser app',
    'retail execution',
    'distributor software',
  ],
  openGraph: {
    type: 'website',
    url: 'https://reshelvs.com',
    siteName: 'Reshelvs',
    title: 'Reshelvs — the operating system for FMCG field teams',
    description:
      'Routes, store visits, on-shelf availability, and field reports — in one platform built for merchandisers, supervisors, and brands.',
    // OG image auto-generated by app/opengraph-image.tsx (next/og).
  },
  twitter: {
    card: 'summary_large_image',
    creator: '@reshelvs',
    title: 'Reshelvs — the OS for FMCG field teams',
    description:
      'Routes, visits, on-shelf availability, and field reports — in one platform.',
  },
  icons: {
    icon: { url: '/reshelvs_ios_logo.png', type: 'image/png', sizes: '1024x1024' },
    apple: '/reshelvs_ios_logo.png',
  },
};

const orgJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'Reshelvs',
  url: 'https://reshelvs.com',
  logo: 'https://reshelvs.com/reshelvs_ios_logo.png',
  sameAs: [
    'https://twitter.com/reshelvs',
    'https://linkedin.com/company/reshelvs',
    'https://github.com/reshelvs',
  ],
};

const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Reshelvs',
  url: 'https://reshelvs.com',
  description:
    'The operating system for FMCG field teams. Routes, store visits, on-shelf availability, and field reports — in one platform.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // No hardcoded `dark` class on <html> any more — the boot script
    // and next-themes manage it together. `suppressHydrationWarning` is
    // required by next-themes because the script mutates the html
    // element before React hydrates.
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: noFlashScript }} />
        {/* If JS never runs, scroll-reveal content must still be visible. */}
        <noscript>
          <style>{`.fade-in{opacity:1 !important;transform:none !important;}`}</style>
        </noscript>
      </head>
      <body className="min-h-screen bg-bg text-fg font-sans antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <ThemeProvider>
          {/* Skip link — first tab stop, lets keyboard users bypass the
              fixed announcement bar + nav (WCAG 2.4.1). Hidden until focused. */}
          <a
            href="#main-content"
            className="focus-ring fixed left-4 top-4 z-[100] -translate-y-24 rounded-md border border-border bg-bg-surface px-4 py-2 text-sm font-medium text-fg transition-transform focus:translate-y-0"
          >
            Skip to content
          </a>
          <div className="fixed inset-x-0 top-0 z-50">
            <AnnouncementBar />
            <Navbar />
          </div>
          <main id="main-content" tabIndex={-1} className="pt-[88px]">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
